### ISSUE TITLE
Inheriting fluxorcomponent

### ISSUE THREAD

**Issue by carlblanchard** [mrpmorris/Fluxor#51] opened 2020-07-02 15:21 UTC
Loving the library, good work. 
This is probably PEBKAC but if you don't ask you don't know. 

My parent component 'A', currently inherits my base component 'B'. I tried updating my base component 'B' to derive from your Fluxorcomponent but sadly It seems I have to directly inherit your Fluxorcomponent in my main component 'A', otherwise, nothing refreshes when the state changes. Why is this? 

Do you have any examples of implementing when I can't inherit your FluxorComponent.

**Comment by mrpmorris** [comment] 2020-07-02 17:37
You can get notifications using this event https://github.com/mrpmorris/Fluxor/blob/master/Source/Fluxor/IState.cs#L31

But don't forget to implement IDisposable and remove your subscription. 

If any class in the hierarchy is FluxorComponent then it should all work automatically. If it isn't, can you provide me with an example app?

**Comment by mrpmorris** [comment] 2020-07-10 08:35
I'll close this for now. Let me know if the problem isn't resolved and I'll reopen it.

**Closed by mrpmorris** 2020-07-10 08:35 UTC

**Comment by dingdonglars** [comment] 2020-07-21 21:24
I am just getting my feet wet with Fluxor and I find it indeed very intuitive and accessible! Thx!

Just fell over this issue since my Fluxor component did not update either. This was my fault because I had implemented an override of OnInitialized() and forgot to call up to base.OnInitialized(). Thus the subscription to state changes in the OnInitialized() method in FluxorComponent base class was never done.

Maybe @carlblanchard had the same issue?

**Comment by mrpmorris** [comment] 2020-07-22 06:41
Could be. It wouldn't be the first time. This is why I always call the base, even if I know it does nothing :)

**Comment by carlblanchard** [comment] 2020-07-23 13:24
For me, it turned out that Blazor was erroring before hitting my dispatcher.
